name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Nuxt Lazytube 🙌
        Please fill in the details below.

  - type: dropdown
    id: platform
    attributes:
      label: Which video platform are you using?
      options:
        - YouTube
        - Vimeo
        - Both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
      placeholder: Explain the issue clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true